package day3OfJavaProggramming;

public class ConstrructorsExample// it is used to initialize an object
{
	
	
	@Override
	public String toString() {
		return "ConstrructorsExample object";
	}// this block of code is generated by right click->source->generate toString(); to get the block of code by default.
// here we are printing the obj but to print msg as follows by creating the obj as a class name as a method
	
	ConstrructorsExample()
	{
		this(8);// this() should be in the first line of the block of code or constructor.
		System.out.println("This is an example for the constructor method :"); // this will execute first as the static block will be execute first in a java program. 
	}
	
	// constructor overloading:- same name with different arguments as follows:
	
	ConstrructorsExample(int lord)
	{
		this("Rukmini");
		System.out.println("Believe in Radh Krishna he will do the rest.he is "+lord+" avatar");
	}
	ConstrructorsExample(String name)
	{
		System.out.println("Krishna has 8 wifes one is :"+name);
	}
	
	
	public static void main(String[] args) 
	{
		ConstrructorsExample ce = new ConstrructorsExample();// or new ConstrructorsExample(); for execution 
		System.out.println(ce.toString()); // it will give address and the JVM will create just obj.
		// to print the msg instead of the address,then we need to do method override
		//new ConstrructorsExample(8);
		//new ConstrructorsExample("Rukmini");
	// "this()" is a key word which is used to call only one obj to save memory we can use This keyword 
	
	}
	
	
	

}
